### PR TITLE
[WIP] Create React App-ifying 

### PR DESCRIPTION
**Pull request by brandonkrull**
Starting the conversion of this project to a create-react-app that we can easily link into a ci/cd to something like Vercel, Heroku, Netlify etc.

### CODE REVIEW

**Comment by ryanmercadante** [comment]
Hi Brandon! I had also started working on transitioning this to React. What are your thoughts on using Next.js rather than Create React App? I find it more complete to work with, can easily deploy to Vercel for free, has file based routing built in, and is overall a better developer experience in my opinion. I could make a pull request with my code for setting up Next.js and you can add your Material UI work. Thoughts?

**Comment by brandonkrull** [comment]
hey @ryanmercadante yea that's not a bad idea at all. how far along are you? if you want you can merge your stuff in here or vice versa. let me know. i do like vercel and it can accommodate CRA but next.js would also be fine 👍

**Comment by ryanmercadante** [comment]
> hey @ryanmercadante yea that's not a bad idea at all. how far along are you? if you want you can merge your stuff in here or vice versa. let me know. i do like vercel and it can accommodate CRA but next.js would also be fine 👍

I mainly have Next setup, if you want I can add a PR for the next specific stuff with material ui setup, and you can add your work that youve done on the homepage with material ui.

Im finishing up some work but I'll submit my PR in the next few hours

**Comment by ryanmercadante** [comment]
@brandonkrull Check out my PR https://github.com/yoheinakajima/tangonft/pull/2

Setup Next boilerplate with material ui. Have the intial web3 connection made and am just displaying the wallet address on the page after clicking the "connect with metamask" button. Please leave as many comments as necessary, I want to make sure we are starting from a good spot :)

**Comment by brandonkrull** [comment]
closing in favor of using pr #2

**Pull request closed without merging**
